steps:
  # Step 1: Download Dockerfile from GCS to build context
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://cdsc_pipelines/campylobacter_analysis/dockerfile', './Dockerfile']

  # Step 2: Download run_scripts.R from GCS to build context
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://cdsc_pipelines/campylobacter_analysis/run_scripts.R', './run_scripts.R']

  # Step 3: Download key.json from GCS (if required)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://cdsc_pipelines/campylobacter_analysis/secrets/cdsc-projects-000b39cf47df.json', './key.json']

  # Step 4: Download entrypoint.sh from GCS (if required)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://cdsc_pipelines/campylobacter_analysis/entrypoint.sh', './entrypoint.sh']

  # Step 5: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'europe-west2-docker.pkg.dev/cdsc-projects/campylobacter-analysis-artreg/campylobacter-analysis-img', '.'
    ]

images:
  - 'europe-west2-docker.pkg.dev/cdsc-projects/campylobacter-analysis-artreg/campylobacter-analysis-img'
