steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://cdsc_pipelines/campylobacter_analysis/dockerfile', './Dockerfile']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://cdsc_pipelines/campylobacter_analysis/run_scripts.R', './run_scripts.R']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://cdsc_pipelines/campylobacter_analysis/secrets/cdsc-projects-000b39cf47df.json', './key.json']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://cdsc_pipelines/campylobacter_analysis/entrypoint.sh', './entrypoint.sh']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'europe-west2-docker.pkg.dev/cdsc-projects/campylobacter-analysis-artreg/campylobacter-analysis-img', '.'
    ]

images:
  - 'europe-west2-docker.pkg.dev/cdsc-projects/campylobacter-analysis-artreg/campylobacter-analysis-img'
