  name: Sync to Google Cloud Storage

  on:
    push:
      branches:
        - main

  jobs:
    sync:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Authenticate with Google Cloud
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.gcp_cdsc_multipipelines_seracc }}
            cleanup_credentials: false

        - name: Debug - List Files
          run: |
            echo "Current directory: $(pwd)"
            find . -name '*gha-creds*.json'

        # - name: Sync Repository to GCS
        #   uses: google-github-actions/upload-cloud-storage@v1
        #   with:
        #     path: .
        #     destination: gcp-cdsc-multipipelines
        #     parent: false
        #     process_gcloudignore: true

        - name: Activate service account
          run: |
            gcloud auth activate-service-account --key-file="${{ steps.auth.outputs.credentials_file_path }}"

        - name: Sync (mirror) to GCS
          run: |
            gsutil -m rsync -d -r . gs://gcp-cdsc-multipipelines
              
        - name: Cleanup temp GCP credential
          run: |
            rm -f gha-creds-*.json
