  name: Sync to Google Cloud Storage

  on:
    push:
      branches:
        - main

  jobs:
    sync:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Authenticate with Google Cloud
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.gcp_cdsc_multipipelines_seracc }}
            cleanup_credentials: false

        - name: Debug - List Files
          run: |
            echo "Current directory: $(pwd)"
            find . -name '*gha-creds*.json'

        - name: Delete old files to compromise rename (except _credential/)
          run: |
            # List all objects except _credential/*
            gsutil ls gs://gcp-cdsc-multipipelines/** | grep -v '^gs://gcp-cdsc-multipipelines/_credential/' > to-delete.txt || true        
            # Delete them
            if [[ -s to-delete.txt ]]; then
              cat to-delete.txt | xargs gsutil rm
            else
              echo "No files to delete."
            fi
            
        - name: Upload (respects .gcloudignore)
          uses: google-github-actions/upload-cloud-storage@v1
          with:
            path: .
            destination: gcp-cdsc-multipipelines
            parent: false
            process_gcloudignore: true

        - name: Find GCP credentials file
          id: find-creds
          run: |
            echo "CREDENTIAL_PATH=$(find . -name 'gha-creds-*.json')" >> $GITHUB_OUTPUT

        - name: Activate service account manually
          run: |
            gcloud auth activate-service-account --key-file="${{ steps.find-creds.outputs.CREDENTIAL_PATH }}"
             
        - name: Cleanup temp GCP credential
          run: |
            rm -f gha-creds-*.json
